### ISSUE TITLE
Handler request has an issue. 

### ISSUE THREAD

**Issue by amirhoseinsh** [wish-team/ario#1]
Handler request has an issue. 

data: "Traceback (most recent call last):↵  File "/Users/amirhosein/Documents/wishwork/wishwork-begins/wishwork_begins/venv/lib/python3.8/site-packages/ario/router.py", line 182, in __call__↵    ret = func(req, resp)↵  File "/Users/amirhosein/Documents/wishwork/wishwork-begins/wishwork_begins/venv/lib/python3.8/site-packages/ario/content.py", line 11, in wrapper↵    body = handler(request, response, *args)↵TypeError: 'NoneType' object is not callable↵"

**Comment by amirhoseinsh** [comment]
you should first define `@documentation.add_doc()` and then define wrapper like `json`
